version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.12.7
    - 7.13.0
    - 7.13.8
  - dependency-name: "@babel/plugin-proposal-nullish-coalescing-operator"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.13.0
  - dependency-name: np
    versions:
    - 7.2.0
    - 7.3.0
    - 7.4.0
  - dependency-name: "@babel/plugin-proposal-json-strings"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: "@babel/plugin-proposal-export-default-from"
    versions:
    - 7.12.1
  - dependency-name: "@babel/plugin-proposal-do-expressions"
    versions:
    - 7.12.1
  - dependency-name: "@babel/plugin-proposal-function-sent"
    versions:
    - 7.12.1
  - dependency-name: "@babel/plugin-proposal-export-namespace-from"
    versions:
    - 7.12.1
